dataset_dir: "dataset"
model_out: "trained_model.pt"
infer_out: "output.csv"
model: "trained_model.pt"
base_dir: null

hydra:
  run:
    dir: .
  job:
    chdir: False
  output_subdir: null

logging:
  mlflow_addr: 127.0.0.1:8080

defaults:
  - _self_
  - experiment: base_experiment
