dataset_dir: "dataset"
model_out_path: "trained_model.pt"
model_inp: null
base_dir: null

hydra:
  job:
    chdir: False
  output_subdir: null

logging:
  mlflow_addr: 127.0.0.1:8080

defaults:
  - _self_
  - experiment: base_experiment